routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/article', 'ArticleController');

Auth::routes();

Route::get('/home', 'ArticleController@article');
Route::get('/home/{id}', 'ArticleController@showArticle');

Route::get('/user/{id}', 'userController@index');
Route::get('/user/{id}/show', 'userController@show1');

Route::get('/profil', 'userController@index1');
Route::post('/profil', 'userController@store');
Route::get('/profil/{id}', 'userController@show');
Route::get('/profil/{id}/edit', 'userController@edit');
Route::put('/profil/{id}', 'userController@update');
Route::delete('/profil/{id}', 'userController@destroy');

Route::get('/artikel', 'ArticleController@examples');

Route::post('/comments', 'CommentController@store');
Route::delete('/comments/{id}', 'CommentController@destroy')->name('comment.destroy');

Route::get('/myprofile', 'userController@myprofile');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //
    protected $fillable = ['title','article','thumbnail','user_id'];
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
    
    public function tag()
    {
        return $this->hasMany('App\Article_tag', 'article_id');    
    }
    
    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'article_tag', 'article_id', 'tag_id');    
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use App\Article;
use App\User;
use App\Tag;
Use Alert;


class ArticleController extends Controller
{
    public function __construct(){

        $this->middleware('auth')->except('article','showArticle');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $article = Article::all();

        $data['article'] = $article;
        $data['headertitle'] = 'Articles';

        return view('dashboard.pages.article.article-table', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['headertitle'] = 'Create Article';

        return view('dashboard.pages.article.article-create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'thumbnail' => 'required|image|file|max:7000',
            'title' => 'required',
            'article' => 'required'
        ]);

        $input['title'] = $request->title;
        $input['article'] = $request->article;
        $input['user_id'] = Auth::id();

        $tags = $request->tags;
        // Array Tags
        $tags_arr = explode(',', $tags);
        
        $tag_ids = [];
        foreach ($tags_arr as $tag_name ) {
            $tag = Tag::where('tag_name', $tag_name)->first();
            if($tag){
                $tag_ids[] = $tag->id;
            }else{
                $new_tag = Tag::create(['tag_name'=>$tag_name]);
                $tag_ids[] = $new_tag->id;
            }
        }

        // Name File
        $namefile = str_replace(' ', '_', $request->title)."-".date('YmdHis').".".$request->file('thumbnail')->getClientOriginalExtension();
        // Upload File       
        $path = Storage::putFileAs(
            'public/thumbnail', $request->file('thumbnail'), $namefile
        );

        $input['thumbnail'] = $namefile;

        $action = Article::create($input);

        $action->tags()->sync($tag_ids);

        Alert::success('Success', 'Create Article Success');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        if($article->user_id==Auth::id()){
            $tags = $article->tags;
            $data['article'] = $article;
            $data['tags'] = $tags;
            $data['headertitle'] = 'Edit Article';
            
            return view('dashboard.pages.article.article-edit', $data);
        }else{
            Alert::error('Error', 'Somenthing was wrong!');
            return redirect('/article');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'thumbnail' => 'image|file|max:7000',
            'title' => 'required',
            'article' => 'required'
        ]);
        
        if($request->hasFile('thumbnail')){
            // Name File
            $namefile = str_replace(' ', '_', $request->title)."-".date('YmdHis').".".$request->file('thumbnail')->getClientOriginalExtension();
            // Upload File       
            $path = Storage::putFileAs(
                'public/thumbnail', $request->file('thumbnail'), $namefile
            );
            $update['thumbnail'] = $namefile;

        }

        $tags = $request->tags;
        // Array Tags
        $tags_arr = explode(',', $tags);
        
        $tag_ids = [];
        foreach ($tags_arr as $tag_name ) {
            $tag = Tag::where('tag_name', $tag_name)->first();
            if($tag){
                $tag_ids[] = $tag->id;
            }else{
                $new_tag = Tag::create(['tag_name'=>$tag_name]);
                $tag_ids[] = $new_tag->id;
            }
        }

        $id_pivot = explode(',', $request->pivot);

        $update['title'] = $request->title;
        $update['article'] = $request->article;
        
        $action = Article::where('id', $id)->update($update);

        // $action->tags()->sync($tag_ids);
        // $action->tags()->newPivotStatement()->where('article_id', $id)->update($tag_ids);
        // $action->tags()->updateExistingPivot($id_pivot, $tag_ids);
        Alert::success('Article Updated', 'Success Update Article!');

        return redirect('/article/'.$id.'/edit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $delete = Article::where('id', $id)->delete();
        
        Alert::success('Deleted', 'Article Deleted!');
        return redirect()->back()->with('success','Deleted Success');
    }

    public function article()
    {
        $article = Article::all();

        $data['articles'] = $article;
        $data['headertitle'] = 'News & Article';

        return view('front-page.pages.article-card', $data);
    }

    public function showArticle($id)
    {
        $article = Article::find($id);

        $data['article'] = $article;
        $data['headertitle'] = 'News & Article';

        return view('front-page.pages.article', $data);
    }

    public function examples(){
        return view ('home');
    }
}

resources/views/dashboard/pages/article/article-create.blade.php
@extends('dashboard.layouts.master')

@push('css')
<link rel="stylesheet" href="{{ asset('template/dashboard/adminlte/plugins/summernote/summernote-bs4.min.css') }}">
@endpush

@section('content')
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Create Article</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item mr-5 "><a href="/artikel">Artikel Laravel</a></li>
              
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3>Create Article</h3>
            </div>
            <form role="form" action="/article" method="post" enctype='multipart/form-data'>
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control col-md-6" id="title" name="title" placeholder="Title" value="{{ old('title') }}">
                        <span class="text-danger">{{ $errors->first('title') }}</span>
                    </div>
                    <div class="form-group">
                        <label for="tags">Tags</label>
                        <input type="text" class="form-control col-md-6" id="tags" name="tags" placeholder="Tags *use ',' to separate tags (eg. PHP, JavaScript, Python )" value="{{ old('tags') }}">
                        <span class="text-danger">{{ $errors->first('tags') }}</span>
                    </div>
                    <div class="form-group">
                        <label for="tags">Thumbnail</label>
                        <input type="file" class="form-control-file col-md-6 " id="thumbnail" name="thumbnail" >
                        <span class="text-danger">{{ $errors->first('thumbnail') }}</span>
                    </div>
                    <div class="form-group">
                        <label for="article">Article</label>
                        <textarea id="summernote" name="article">{{ old('article') }}</textarea>
                        <span class="text-danger">{{ $errors->first('article') }}</span>
                    </div>
                    <div class="form-group">
                        @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success')}}
                        </div>
                        @endif
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </section>
    <!-- /.content -->
@endsection
    
@push('script')
<script src="{{ asset('template/dashboard/adminlte/plugins/summernote/summernote-bs4.js') }}"></script>
<script src="{{ asset('template/dashboard/adminlte/plugins/summernote/summernote-bs4.min.js') }}"></script>
<script>
$(function () {
    $("#summernote").summernote({
       placeholder : "Article",
       toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']]
        ],
        height: 300,
        minHeight: null,
        maxHeight: null,
        focus: true 
    });
});
</script>
@endpush

resources/views/dashboard/pages/article/article-edit.blade.php
@extends('dashboard.layouts.master')

@push('css')
<link rel="stylesheet" href="{{ asset('template/dashboard/adminlte/plugins/summernote/summernote-bs4.min.css') }}">
@endpush

@section('content')
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Create Article</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/artikel">Article</a></li>
              <li class="breadcrumb-item active">Create Article</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3>Create Article</h3>
            </div>
            <form role="form" action="{{ route('article.update', $article->id)}}" method="post" enctype='multipart/form-data'>
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control col-md-6" id="title" name="title" placeholder="Title" value="{{ $article->title }}">
                        <span class="text-danger">{{ $errors->first('title') }}</span>
                    </div>
                    <div class="form-group">
                        <label for="tags">Tags</label>
                        <input type="text" class="form-control col-md-6" id="tags" name="tags" placeholder="Tags *use ',' to separate tags (eg. PHP, JavaScript, Python )" value="@foreach($tags as $tag){{$tag->tag_name}},@endforeach">
                        <span class="text-danger">{{ $errors->first('tags') }}</span>
                    </div>
                    <div class="form-group">
                        <label for="tags">Thumbnail</label>
                        <input type="file" class="form-control-file col-md-6 " id="thumbnail" name="thumbnail" >
                        <span class="text-muted">*empty if you don't want to change the thumbnail</span>
                        <span class="text-danger">{{ $errors->first('thumbnail') }}</span>
                    </div>
                    <div class="form-group">
                        <label for="article">Article</label>
                        <textarea id="summernote" name="article">{{ $article->article }}</textarea>
                        <span class="text-danger">{{ $errors->first('article') }}</span>
                    </div>
                    <div class="form-group">
                    <input type="hidden" id="pivot" name="pivot" value="@foreach($article->tag as $pivot) {{ $pivot->id }} @endforeach">
                        @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success')}}
                        </div>
                        @endif
                        @if (session('error'))
                        <div class="alert alert-danger">
                            {{ session('error')}}
                        </div>
                        @endif
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Edit</button>
                </div>
            </form>
        </div>
    </section>
    <!-- /.content -->
@endsection
    
@push('script')
<script src="{{ asset('template/dashboard/adminlte/plugins/summernote/summernote-bs4.js') }}"></script>
<script src="{{ asset('template/dashboard/adminlte/plugins/summernote/summernote-bs4.min.js') }}"></script>
<script>
$(function () {
    $("#summernote").summernote({
       placeholder : "Article",
       toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']]
        ],
        height: 300,
        minHeight: null,
        maxHeight: null,
        focus: true 
    });
});
</script>
@endpush

resources/views/dashboard/pages/article/article-table.blade.php
@extends('dashboard.layouts.master')

@push('css')
  <link rel="stylesheet" href="{{ asset('template/dashboard/adminlte/plugins/sweetalert2/sweetalert2.all.min.js')}}">
@endpush

@section('content')
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Article List</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/artikel">Article</a></li>
              <li class="breadcrumb-item active">Article List</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3>Articles</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Title</th>
                            <th>Article</th>
                            <th>Thumbnail</th>
                            <th>Author</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                           $no = 1; 
                        @endphp
                        @foreach ($article as $row)                            
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $row->title }}</td>
                            <td>{!! Str::limit($row->article, 50, '...') !!}</td>
                            <td>
                              <img src="{{ asset("storage/thumbnail/{$row->thumbnail}") }}" style=" height: 70px;">
                            </td>
                            <td>{{ $row->user->name }}</td>
                            <td class="text-center">
                              <div class="btn-group">
                                <a href="{{ url('/home/'.$row->id)}}" class="btn btn-info"><i class="fas fa-eye"></i></a>
                                @if ($row->user_id == Auth::id())
                                <a href="{{ url('/article/'.$row->id.'/edit') }}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                                <form action="{{ route('article.destroy', $row->id)}}" method="POST">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                </form>                                    
                                @endif
                              </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </section>
    <!-- /.content -->
@endsection

@push('script')
<script src="{{ asset('template/dashboard/adminlte/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('template/dashboard/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script src="{{ asset('template/dashboard/adminlte/plugins/sweetalert2/sweetalert2.all.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
        "responsive": true
    });
});
</script>
@endpush